import { NextResponse } from 'next/server';

// Service IDs
const REALDEBRID_SERVICE = 'realdebrid';
const ALLDEBRID_SERVICE = 'alldebrid';
const PREMIUMIZE_SERVICE = 'premiumize';
const DEBRIDLINK_SERVICE = 'debridlink';
const TORBOX_SERVICE = 'torbox';
const EASYDEBRID_SERVICE = 'easydebrid';
const DEBRIDER_SERVICE = 'debrider';
const PUTIO_SERVICE = 'putio';
const OFFCLOUD_SERVICE = 'offcloud';
const PIKPAK_SERVICE = 'pikpak';
const SEEDR_SERVICE = 'seedr';
const EASYNEWS_SERVICE = 'easynews';

// Resource types
const STREAM_RESOURCE = 'stream';
const CATALOG_RESOURCE = 'catalog';
const META_RESOURCE = 'meta';
const SUBTITLES_RESOURCE = 'subtitles';

// Stream types
const P2P_STREAM_TYPE = 'p2p';
const DEBRID_STREAM_TYPE = 'debrid';
const USENET_STREAM_TYPE = 'usenet';
const HTTP_STREAM_TYPE = 'http';
const LIVE_STREAM_TYPE = 'live';

// Preset categories - must match frontend constants (metaCatalogs not meta_catalogs)
const CATEGORY_STREAMS = 'streams';
const CATEGORY_SUBTITLES = 'subtitles';
const CATEGORY_META_CATALOGS = 'metaCatalogs';
const CATEGORY_MISC = 'misc';

// Common debrid services
const COMMON_DEBRID_SERVICES = [REALDEBRID_SERVICE, ALLDEBRID_SERVICE, PREMIUMIZE_SERVICE, TORBOX_SERVICE, DEBRIDLINK_SERVICE, EASYDEBRID_SERVICE];
const EXTENDED_DEBRID_SERVICES = [...COMMON_DEBRID_SERVICES, DEBRIDER_SERVICE, OFFCLOUD_SERVICE, PIKPAK_SERVICE];

// Services data
const services = {
  [REALDEBRID_SERVICE]: {
    id: REALDEBRID_SERVICE,
    name: 'Real-Debrid',
    shortName: 'RD',
    knownNames: ['RD', 'Real Debrid', 'RealDebrid', 'Real-Debrid'],
    signUpText: "Don't have an account? [Sign up here](https://real-debrid.com/?id=9483829)",
    credentials: [{ id: 'apiKey', name: 'API Key', description: 'Get it from [here](https://real-debrid.com/apitoken)', type: 'password', required: true }],
  },
  [ALLDEBRID_SERVICE]: {
    id: ALLDEBRID_SERVICE,
    name: 'AllDebrid',
    shortName: 'AD',
    knownNames: ['AD', 'All Debrid', 'AllDebrid'],
    signUpText: "Don't have an account? [Sign up here](https://alldebrid.com/?uid=3n8qa&lang=en)",
    credentials: [{ id: 'apiKey', name: 'API Key', description: 'Create one [here](https://alldebrid.com/apikeys)', type: 'password', required: true }],
  },
  [PREMIUMIZE_SERVICE]: {
    id: PREMIUMIZE_SERVICE,
    name: 'Premiumize',
    shortName: 'PM',
    knownNames: ['PM', 'Premiumize'],
    signUpText: "Don't have an account? [Sign up here](https://www.premiumize.me/register)",
    credentials: [{ id: 'apiKey', name: 'API Key', description: 'Get it from [here](https://www.premiumize.me/account)', type: 'password', required: true }],
  },
  [DEBRIDLINK_SERVICE]: {
    id: DEBRIDLINK_SERVICE,
    name: 'Debrid-Link',
    shortName: 'DL',
    knownNames: ['DL', 'Debrid Link', 'DebridLink'],
    signUpText: "Don't have an account? [Sign up here](https://debrid-link.com/id/EY0JO)",
    credentials: [{ id: 'apiKey', name: 'API Key', description: 'Get it from [here](https://debrid-link.com/webapp/apikey)', type: 'password', required: true }],
  },
  [TORBOX_SERVICE]: {
    id: TORBOX_SERVICE,
    name: 'TorBox',
    shortName: 'TB',
    knownNames: ['TB', 'TorBox', 'Torbox'],
    signUpText: "Don't have an account? [Sign up here](https://torbox.app/subscription?referral=9ca21adb-dbcb-4fb0-9195-412a5f3519bc)",
    credentials: [{ id: 'apiKey', name: 'API Key', description: 'Get it from [here](https://torbox.app/settings)', type: 'password', required: true }],
  },
  [EASYDEBRID_SERVICE]: {
    id: EASYDEBRID_SERVICE,
    name: 'EasyDebrid',
    shortName: 'ED',
    knownNames: ['ED', 'Easy Debrid', 'EasyDebrid'],
    signUpText: "Don't have an account? [Sign up here](https://easydebrid.com)",
    credentials: [{ id: 'apiKey', name: 'API Key', description: 'Your EasyDebrid API key', type: 'password', required: true }],
  },
  [DEBRIDER_SERVICE]: {
    id: DEBRIDER_SERVICE,
    name: 'Debrider',
    shortName: 'DR',
    knownNames: ['DR', 'Debrider'],
    credentials: [{ id: 'apiKey', name: 'API Key', description: 'Your Debrider API key', type: 'password', required: true }],
  },
  [PUTIO_SERVICE]: {
    id: PUTIO_SERVICE,
    name: 'Put.io',
    shortName: 'PUT',
    knownNames: ['PUT', 'Put.io', 'Putio'],
    signUpText: "Don't have an account? [Sign up here](https://put.io)",
    credentials: [
      { id: 'clientId', name: 'Client ID', description: 'Your Put.io OAuth Client ID', type: 'string', required: true },
      { id: 'clientSecret', name: 'Client Secret', description: 'Your Put.io OAuth Client Secret', type: 'password', required: true },
    ],
  },
  [OFFCLOUD_SERVICE]: {
    id: OFFCLOUD_SERVICE,
    name: 'Offcloud',
    shortName: 'OC',
    knownNames: ['OC', 'Offcloud'],
    signUpText: "Don't have an account? [Sign up here](https://offcloud.com)",
    credentials: [{ id: 'apiKey', name: 'API Key', description: 'Your Offcloud API key', type: 'password', required: false }],
  },
  [PIKPAK_SERVICE]: {
    id: PIKPAK_SERVICE,
    name: 'PikPak',
    shortName: 'PKP',
    knownNames: ['PKP', 'PikPak'],
    credentials: [
      { id: 'email', name: 'Email', type: 'string', required: true },
      { id: 'password', name: 'Password', type: 'password', required: true },
    ],
  },
  [SEEDR_SERVICE]: {
    id: SEEDR_SERVICE,
    name: 'Seedr',
    shortName: 'SDR',
    knownNames: ['SDR', 'Seedr'],
    credentials: [{ id: 'encodedToken', name: 'Encoded Token', type: 'password', required: true }],
  },
  [EASYNEWS_SERVICE]: {
    id: EASYNEWS_SERVICE,
    name: 'Easynews',
    shortName: 'EN',
    knownNames: ['EN', 'Easynews'],
    signUpText: "Don't have an account? [Sign up here](https://www.easynews.com)",
    credentials: [
      { id: 'username', name: 'Username', type: 'string', required: true },
      { id: 'password', name: 'Password', type: 'password', required: true },
    ],
  },
};

// Helper for basic options
const basicOptions = (name: string) => [
  { id: 'name', name: 'Name', description: 'What to call this addon', type: 'string', required: true, default: name },
  { id: 'timeout', name: 'Timeout (ms)', description: 'Request timeout', type: 'number', required: true, default: 10000, constraints: { min: 1000, max: 60000 } },
];

// All presets - comprehensive list matching presetManager.ts
const presets = [
  // === STREAM ADDONS ===
  {
    ID: 'torrentio',
    NAME: 'Torrentio',
    LOGO: 'https://torrentio.strem.fun/images/logo_v1.png',
    URL: 'https://torrentio.strem.fun',
    DESCRIPTION: 'Provides torrent streams from a multitude of providers and has debrid support.',
    SUPPORTED_SERVICES: [REALDEBRID_SERVICE, PREMIUMIZE_SERVICE, ALLDEBRID_SERVICE, TORBOX_SERVICE, EASYDEBRID_SERVICE, PUTIO_SERVICE, DEBRIDLINK_SERVICE, OFFCLOUD_SERVICE],
    SUPPORTED_STREAM_TYPES: [P2P_STREAM_TYPE, DEBRID_STREAM_TYPE],
    SUPPORTED_RESOURCES: [STREAM_RESOURCE, META_RESOURCE, CATALOG_RESOURCE],
    OPTIONS: basicOptions('Torrentio'),
    CATEGORY: CATEGORY_STREAMS,
  },
  {
    ID: 'comet',
    NAME: 'Comet',
    LOGO: 'https://i.ibb.co/LVGNJ0s/icon.jpg',
    URL: 'https://comet.elfhosted.com',
    DESCRIPTION: "Stremio's fastest Torrent/Debrid addon",
    SUPPORTED_SERVICES: EXTENDED_DEBRID_SERVICES,
    SUPPORTED_STREAM_TYPES: [P2P_STREAM_TYPE, DEBRID_STREAM_TYPE],
    SUPPORTED_RESOURCES: [STREAM_RESOURCE],
    OPTIONS: basicOptions('Comet'),
    CATEGORY: CATEGORY_STREAMS,
  },
  {
    ID: 'mediafusion',
    NAME: 'MediaFusion',
    LOGO: 'https://raw.githubusercontent.com/mhdzumair/MediaFusion/refs/heads/main/resources/images/mediafusion_logo.png',
    URL: 'https://mediafusion.elfhosted.com',
    DESCRIPTION: 'Universal Stremio Add-on for Movies, Series, Live TV & Sports Events',
    SUPPORTED_SERVICES: [...EXTENDED_DEBRID_SERVICES, SEEDR_SERVICE],
    SUPPORTED_STREAM_TYPES: [P2P_STREAM_TYPE, DEBRID_STREAM_TYPE],
    SUPPORTED_RESOURCES: [STREAM_RESOURCE, CATALOG_RESOURCE, META_RESOURCE],
    OPTIONS: basicOptions('MediaFusion'),
    CATEGORY: CATEGORY_STREAMS,
  },
  {
    ID: 'stremthruTorz',
    NAME: 'StremThru Torz',
    LOGO: 'https://emojiapi.dev/api/v1/sparkles/256.png',
    URL: 'https://stremthru.elfhosted.com',
    DESCRIPTION: 'Stream torrents through StremThru with debrid support.',
    SUPPORTED_SERVICES: COMMON_DEBRID_SERVICES,
    SUPPORTED_STREAM_TYPES: [DEBRID_STREAM_TYPE],
    SUPPORTED_RESOURCES: [STREAM_RESOURCE],
    OPTIONS: basicOptions('StremThru Torz'),
    CATEGORY: CATEGORY_STREAMS,
  },
  {
    ID: 'stremthruStore',
    NAME: 'StremThru Store',
    LOGO: 'https://emojiapi.dev/api/v1/sparkles/256.png',
    URL: 'https://stremthru.elfhosted.com',
    DESCRIPTION: 'Access your debrid library through catalogs and streams.',
    SUPPORTED_SERVICES: COMMON_DEBRID_SERVICES,
    SUPPORTED_STREAM_TYPES: [DEBRID_STREAM_TYPE],
    SUPPORTED_RESOURCES: [STREAM_RESOURCE, CATALOG_RESOURCE],
    OPTIONS: basicOptions('StremThru Store'),
    CATEGORY: CATEGORY_STREAMS,
  },
  {
    ID: 'sootio',
    NAME: 'Sootio',
    LOGO: "data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 100 100'%3E%3Cdefs%3E%3ClinearGradient id='grad' x1='0%25' y1='0%25' x2='100%25' y2='100%25'%3E%3Cstop offset='0%25' style='stop-color:%2364ffda;stop-opacity:1' /%3E%3Cstop offset='100%25' style='stop-color:%2300A7B5;stop-opacity:1' /%3E%3C/linearGradient%3E%3C/defs%3E%3Cpath fill='url(%23grad)' d='M50,5 C74.85,5 95,25.15 95,50 C95,74.85 74.85,95 50,95 C35,95 22.33,87.6 15,76 C25,85 40,85 50,80 C60,75 65,65 65,50 C65,35 55,25 40,25 C25,25 15,40 15,50 C15,55 16,60 18,64 C8.5,58 5,45 5,50 C5,25.15 25.15,5 50,5 Z'/%3E%3C/svg%3E",
    URL: 'https://sootio.elfhosted.com',
    DESCRIPTION: 'Debrid addon with advanced features.',
    SUPPORTED_SERVICES: COMMON_DEBRID_SERVICES,
    SUPPORTED_STREAM_TYPES: [DEBRID_STREAM_TYPE],
    SUPPORTED_RESOURCES: [STREAM_RESOURCE],
    OPTIONS: basicOptions('Sootio'),
    CATEGORY: CATEGORY_STREAMS,
  },
  {
    ID: 'zilean',
    NAME: 'Zilean',
    LOGO: 'https://zilean.elfhosted.com/assets/zilean_logo.jpg',
    URL: 'https://zilean.elfhosted.com',
    DESCRIPTION: 'DMM powered torrent search addon.',
    SUPPORTED_SERVICES: COMMON_DEBRID_SERVICES,
    SUPPORTED_STREAM_TYPES: [P2P_STREAM_TYPE, DEBRID_STREAM_TYPE],
    SUPPORTED_RESOURCES: [STREAM_RESOURCE],
    OPTIONS: basicOptions('Zilean'),
    CATEGORY: CATEGORY_STREAMS,
  },
  {
    ID: 'knaben',
    NAME: 'Knaben',
    LOGO: 'https://knaben.elfhosted.com/assets/knaben_logo.png',
    URL: 'https://knaben.elfhosted.com',
    DESCRIPTION: 'Torrent search addon using Knaben database.',
    SUPPORTED_SERVICES: COMMON_DEBRID_SERVICES,
    SUPPORTED_STREAM_TYPES: [P2P_STREAM_TYPE, DEBRID_STREAM_TYPE],
    SUPPORTED_RESOURCES: [STREAM_RESOURCE],
    OPTIONS: basicOptions('Knaben'),
    CATEGORY: CATEGORY_STREAMS,
  },
  {
    ID: 'torrent-galaxy',
    NAME: 'TorrentGalaxy',
    LOGO: 'https://torrentgalaxy.to/common/images/logo.png',
    URL: 'https://torrentgalaxy.elfhosted.com',
    DESCRIPTION: 'An addon to get debrid results from TorrentGalaxy.',
    SUPPORTED_SERVICES: COMMON_DEBRID_SERVICES,
    SUPPORTED_STREAM_TYPES: [P2P_STREAM_TYPE, DEBRID_STREAM_TYPE],
    SUPPORTED_RESOURCES: [STREAM_RESOURCE],
    OPTIONS: basicOptions('TorrentGalaxy'),
    CATEGORY: CATEGORY_STREAMS,
  },
  {
    ID: 'bitmagnet',
    NAME: 'Bitmagnet',
    LOGO: 'https://cdn.jsdelivr.net/gh/homarr-labs/dashboard-icons/png/bitmagnet.png',
    URL: 'https://bitmagnet.elfhosted.com',
    DESCRIPTION: 'Self-hosted torrent indexer addon.',
    SUPPORTED_SERVICES: COMMON_DEBRID_SERVICES,
    SUPPORTED_STREAM_TYPES: [P2P_STREAM_TYPE, DEBRID_STREAM_TYPE],
    SUPPORTED_RESOURCES: [STREAM_RESOURCE],
    OPTIONS: basicOptions('Bitmagnet'),
    CATEGORY: CATEGORY_STREAMS,
  },
  {
    ID: 'animetosho',
    NAME: 'AnimeTosho',
    LOGO: 'https://animetosho.org/favicon.ico',
    URL: 'https://animetosho.elfhosted.com',
    DESCRIPTION: 'Anime torrents from AnimeTosho.',
    SUPPORTED_SERVICES: COMMON_DEBRID_SERVICES,
    SUPPORTED_STREAM_TYPES: [P2P_STREAM_TYPE, DEBRID_STREAM_TYPE],
    SUPPORTED_RESOURCES: [STREAM_RESOURCE],
    OPTIONS: basicOptions('AnimeTosho'),
    CATEGORY: CATEGORY_STREAMS,
  },
  {
    ID: 'neko-bt',
    NAME: 'nekoBT',
    LOGO: 'https://avatars.githubusercontent.com/u/221218851?v=4',
    URL: 'https://nekobt.elfhosted.com',
    DESCRIPTION: 'An addon to get debrid results from nekoBT.',
    SUPPORTED_SERVICES: COMMON_DEBRID_SERVICES,
    SUPPORTED_STREAM_TYPES: [P2P_STREAM_TYPE, DEBRID_STREAM_TYPE],
    SUPPORTED_RESOURCES: [STREAM_RESOURCE],
    OPTIONS: basicOptions('nekoBT'),
    CATEGORY: CATEGORY_STREAMS,
  },
  {
    ID: 'prowlarr',
    NAME: 'Prowlarr',
    LOGO: 'https://raw.githubusercontent.com/Prowlarr/Prowlarr/refs/heads/develop/Logo/256.png',
    URL: '',
    DESCRIPTION: 'Search your Prowlarr indexers with debrid support.',
    SUPPORTED_SERVICES: COMMON_DEBRID_SERVICES,
    SUPPORTED_STREAM_TYPES: [P2P_STREAM_TYPE, DEBRID_STREAM_TYPE],
    SUPPORTED_RESOURCES: [STREAM_RESOURCE],
    OPTIONS: basicOptions('Prowlarr'),
    CATEGORY: CATEGORY_STREAMS,
  },
  {
    ID: 'jackett',
    NAME: 'Jackett',
    LOGO: 'https://raw.githubusercontent.com/Jackett/Jackett/refs/heads/master/src/Jackett.Common/Content/jacket_medium.png',
    URL: '',
    DESCRIPTION: 'An addon to get debrid results from a Jackett instance.',
    SUPPORTED_SERVICES: COMMON_DEBRID_SERVICES,
    SUPPORTED_STREAM_TYPES: [P2P_STREAM_TYPE, DEBRID_STREAM_TYPE],
    SUPPORTED_RESOURCES: [STREAM_RESOURCE],
    OPTIONS: basicOptions('Jackett'),
    CATEGORY: CATEGORY_STREAMS,
  },
  {
    ID: 'nzbhydra',
    NAME: 'NZBHydra',
    LOGO: 'https://raw.githubusercontent.com/theotherp/nzbhydra2/refs/heads/master/core/ui-src/img/logo.png',
    URL: '',
    DESCRIPTION: 'An addon to get usenet results from a NZBHydra instance.',
    SUPPORTED_SERVICES: [EASYNEWS_SERVICE],
    SUPPORTED_STREAM_TYPES: [USENET_STREAM_TYPE],
    SUPPORTED_RESOURCES: [STREAM_RESOURCE],
    OPTIONS: basicOptions('NZBHydra'),
    CATEGORY: CATEGORY_STREAMS,
  },
  {
    ID: 'stremio-gdrive',
    NAME: 'Stremio GDrive',
    LOGO: 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/12/Google_Drive_icon_%282020%29.svg/1200px-Google_Drive_icon_%282020%29.svg.png',
    URL: 'https://stremio-gdrive.elfhosted.com',
    DESCRIPTION: 'Access content from your Google Drive in Stremio!',
    SUPPORTED_SERVICES: [],
    SUPPORTED_STREAM_TYPES: [HTTP_STREAM_TYPE],
    SUPPORTED_RESOURCES: [STREAM_RESOURCE, CATALOG_RESOURCE],
    OPTIONS: basicOptions('Google Drive'),
    CATEGORY: CATEGORY_STREAMS,
    BUILTIN: true,
  },
  {
    ID: 'jackettio',
    NAME: 'Jackettio',
    LOGO: 'https://raw.githubusercontent.com/Jackett/Jackett/bbea5febd623f6e536e11aa1fa8d6674d8d4043f/src/Jackett.Common/Content/jacket_medium.png',
    URL: 'https://jackettio.elfhosted.com',
    DESCRIPTION: 'Search torrents from Jackett with debrid support.',
    SUPPORTED_SERVICES: COMMON_DEBRID_SERVICES,
    SUPPORTED_STREAM_TYPES: [P2P_STREAM_TYPE, DEBRID_STREAM_TYPE],
    SUPPORTED_RESOURCES: [STREAM_RESOURCE],
    OPTIONS: basicOptions('Jackettio'),
    CATEGORY: CATEGORY_STREAMS,
  },
  {
    ID: 'peerflix',
    NAME: 'Peerflix',
    LOGO: 'https://config.peerflix.mov/static/media/logo.28f42024a3538640d047201d05416a09.svg',
    URL: 'https://peerflix.mov',
    DESCRIPTION: 'Stream torrents directly with Peerflix.',
    SUPPORTED_SERVICES: COMMON_DEBRID_SERVICES,
    SUPPORTED_STREAM_TYPES: [P2P_STREAM_TYPE, DEBRID_STREAM_TYPE],
    SUPPORTED_RESOURCES: [STREAM_RESOURCE],
    OPTIONS: basicOptions('Peerflix'),
    CATEGORY: CATEGORY_STREAMS,
  },
  {
    ID: 'orion',
    NAME: 'Orion',
    LOGO: 'https://orionoid.com/web/images/logo/logo256.png',
    URL: 'https://orion.strem.io',
    DESCRIPTION: 'Orion indexer service for streaming.',
    SUPPORTED_SERVICES: [REALDEBRID_SERVICE, ALLDEBRID_SERVICE, PREMIUMIZE_SERVICE, OFFCLOUD_SERVICE],
    SUPPORTED_STREAM_TYPES: [P2P_STREAM_TYPE, DEBRID_STREAM_TYPE, USENET_STREAM_TYPE],
    SUPPORTED_RESOURCES: [STREAM_RESOURCE],
    OPTIONS: basicOptions('Orion'),
    CATEGORY: CATEGORY_STREAMS,
  },
  {
    ID: 'torrents-db',
    NAME: 'TorrentsDB',
    LOGO: 'https://torrentsdb.elfhosted.com/icon.svg',
    URL: 'https://torrentsdb.elfhosted.com',
    DESCRIPTION: 'Provides torrent streams from scraped torrent providers.',
    SUPPORTED_SERVICES: COMMON_DEBRID_SERVICES,
    SUPPORTED_STREAM_TYPES: [P2P_STREAM_TYPE, DEBRID_STREAM_TYPE],
    SUPPORTED_RESOURCES: [STREAM_RESOURCE],
    OPTIONS: basicOptions('TorrentsDB'),
    CATEGORY: CATEGORY_STREAMS,
  },
  {
    ID: 'streamfusion',
    NAME: 'StreamFusion',
    LOGO: 'https://stream-fusion.stremiofr.com/static/logo-stream-fusion.png',
    URL: 'https://stream-fusion.stremiofr.com',
    DESCRIPTION: 'Stremio addon focusing on french content',
    SUPPORTED_SERVICES: COMMON_DEBRID_SERVICES,
    SUPPORTED_STREAM_TYPES: [P2P_STREAM_TYPE, DEBRID_STREAM_TYPE],
    SUPPORTED_RESOURCES: [STREAM_RESOURCE],
    OPTIONS: basicOptions('StreamFusion'),
    CATEGORY: CATEGORY_STREAMS,
  },
  {
    ID: 'fkstream',
    NAME: 'FKStream',
    LOGO: 'https://raw.githubusercontent.com/Dydhzo/fkstream/refs/heads/main/fkstream/assets/fkstream-logo.jpg',
    URL: 'https://fkstream.stremiofr.com',
    DESCRIPTION: 'French streaming addon.',
    SUPPORTED_SERVICES: [],
    SUPPORTED_STREAM_TYPES: [HTTP_STREAM_TYPE],
    SUPPORTED_RESOURCES: [STREAM_RESOURCE],
    OPTIONS: basicOptions('FKStream'),
    CATEGORY: CATEGORY_STREAMS,
  },
  {
    ID: 'debridio',
    NAME: 'Debridio Scraper',
    LOGO: 'https://debridio.com/logo.png',
    URL: 'https://debridio.com',
    DESCRIPTION: 'Torrent streaming using Debrid providers.',
    SUPPORTED_SERVICES: COMMON_DEBRID_SERVICES,
    SUPPORTED_STREAM_TYPES: [P2P_STREAM_TYPE, DEBRID_STREAM_TYPE],
    SUPPORTED_RESOURCES: [STREAM_RESOURCE],
    OPTIONS: basicOptions('Debridio'),
    CATEGORY: CATEGORY_STREAMS,
  },
  {
    ID: 'torbox',
    NAME: 'TorBox',
    LOGO: 'https://torbox.app/android-chrome-512x512.png',
    URL: 'https://stremio.torbox.app',
    DESCRIPTION: 'Official TorBox addon for Stremio.',
    SUPPORTED_SERVICES: [TORBOX_SERVICE],
    SUPPORTED_STREAM_TYPES: [DEBRID_STREAM_TYPE],
    SUPPORTED_RESOURCES: [STREAM_RESOURCE],
    OPTIONS: basicOptions('TorBox'),
    CATEGORY: CATEGORY_STREAMS,
  },
  {
    ID: 'torbox-search',
    NAME: 'TorBox Search',
    LOGO: 'https://torbox.app/android-chrome-512x512.png',
    URL: 'https://torbox.elfhosted.com',
    DESCRIPTION: 'Search torrents using TorBox API.',
    SUPPORTED_SERVICES: [TORBOX_SERVICE],
    SUPPORTED_STREAM_TYPES: [DEBRID_STREAM_TYPE],
    SUPPORTED_RESOURCES: [STREAM_RESOURCE],
    OPTIONS: basicOptions('TorBox Search'),
    CATEGORY: CATEGORY_STREAMS,
  },
  {
    ID: 'easynews',
    NAME: 'Easynews',
    LOGO: 'https://pbs.twimg.com/profile_images/479627852757733376/8v9zH7Yo_400x400.jpeg',
    URL: 'https://easynews.elfhosted.com',
    DESCRIPTION: 'Stream content from Easynews usenet provider.',
    SUPPORTED_SERVICES: [EASYNEWS_SERVICE],
    SUPPORTED_STREAM_TYPES: [USENET_STREAM_TYPE],
    SUPPORTED_RESOURCES: [STREAM_RESOURCE],
    OPTIONS: basicOptions('Easynews'),
    CATEGORY: CATEGORY_STREAMS,
  },
  {
    ID: 'easynewsPlus',
    NAME: 'Easynews+',
    LOGO: 'https://pbs.twimg.com/profile_images/479627852757733376/8v9zH7Yo_400x400.jpeg',
    URL: 'https://easynewsplus.elfhosted.com',
    DESCRIPTION: 'Enhanced Easynews addon with more features.',
    SUPPORTED_SERVICES: [EASYNEWS_SERVICE],
    SUPPORTED_STREAM_TYPES: [USENET_STREAM_TYPE],
    SUPPORTED_RESOURCES: [STREAM_RESOURCE],
    OPTIONS: basicOptions('Easynews+'),
    CATEGORY: CATEGORY_STREAMS,
  },
  {
    ID: 'easynewsPlusPlus',
    NAME: 'Easynews++',
    LOGO: 'https://pbs.twimg.com/profile_images/479627852757733376/8v9zH7Yo_400x400.jpeg',
    URL: 'https://easynewsplusplus.elfhosted.com',
    DESCRIPTION: 'Easynews++ provides content from Easynews',
    SUPPORTED_SERVICES: [EASYNEWS_SERVICE],
    SUPPORTED_STREAM_TYPES: [USENET_STREAM_TYPE],
    SUPPORTED_RESOURCES: [STREAM_RESOURCE],
    OPTIONS: basicOptions('Easynews++'),
    CATEGORY: CATEGORY_STREAMS,
  },
  {
    ID: 'easynews-search',
    NAME: 'Easynews Search',
    LOGO: 'https://easynews.elfhosted.com/assets/easynews_logo.png',
    URL: 'https://easynews-search.elfhosted.com',
    DESCRIPTION: 'Search Easynews directly.',
    SUPPORTED_SERVICES: [EASYNEWS_SERVICE],
    SUPPORTED_STREAM_TYPES: [USENET_STREAM_TYPE],
    SUPPORTED_RESOURCES: [STREAM_RESOURCE],
    OPTIONS: basicOptions('Easynews Search'),
    CATEGORY: CATEGORY_STREAMS,
  },
  {
    ID: 'usenet-streamer',
    NAME: 'Usenet Streamer',
    LOGO: 'https://raw.githubusercontent.com/Sanket9225/UsenetStreamer/refs/heads/master/assets/icon.png',
    URL: 'https://usenet-streamer.elfhosted.com',
    DESCRIPTION: 'Stream content from usenet providers.',
    SUPPORTED_SERVICES: [EASYNEWS_SERVICE],
    SUPPORTED_STREAM_TYPES: [USENET_STREAM_TYPE],
    SUPPORTED_RESOURCES: [STREAM_RESOURCE],
    OPTIONS: basicOptions('Usenet Streamer'),
    CATEGORY: CATEGORY_STREAMS,
  },
  {
    ID: 'dmm-cast',
    NAME: 'DMM Cast',
    LOGO: 'https://static.debridmediamanager.com/dmmcast.png',
    URL: 'https://dmmcast.elfhosted.com',
    DESCRIPTION: 'Debrid Media Manager Cast addon.',
    SUPPORTED_SERVICES: COMMON_DEBRID_SERVICES,
    SUPPORTED_STREAM_TYPES: [DEBRID_STREAM_TYPE],
    SUPPORTED_RESOURCES: [STREAM_RESOURCE],
    OPTIONS: basicOptions('DMM Cast'),
    CATEGORY: CATEGORY_STREAMS,
  },
  {
    ID: 'nuvio-streams',
    NAME: 'Nuvio Streams',
    LOGO: 'https://raw.githubusercontent.com/tapframe/NuvioStreaming/main/assets/titlelogo.png',
    URL: 'https://nuvio.elfhosted.com',
    DESCRIPTION: 'Free high quality streaming using multiple providers.',
    SUPPORTED_SERVICES: [],
    SUPPORTED_STREAM_TYPES: [HTTP_STREAM_TYPE],
    SUPPORTED_RESOURCES: [STREAM_RESOURCE],
    OPTIONS: basicOptions('Nuvio Streams'),
    CATEGORY: CATEGORY_STREAMS,
  },
  {
    ID: 'webstreamr',
    NAME: 'WebStreamr',
    LOGO: 'https://webstreamr.elfhosted.com/logo.png',
    URL: 'https://webstreamr.elfhosted.com',
    DESCRIPTION: 'Provides HTTP URLs from streaming websites.',
    SUPPORTED_SERVICES: [],
    SUPPORTED_STREAM_TYPES: [HTTP_STREAM_TYPE],
    SUPPORTED_RESOURCES: [STREAM_RESOURCE],
    OPTIONS: basicOptions('WebStreamr'),
    CATEGORY: CATEGORY_STREAMS,
  },
  {
    ID: 'astream',
    NAME: 'AStream',
    LOGO: 'https://raw.githubusercontent.com/Dydhzo/astream/refs/heads/main/astream/assets/astream-logo.jpg',
    URL: 'https://astream.stremiofr.com',
    DESCRIPTION: "Addon non officiel pour accéder au contenu d'Anime-Sama",
    SUPPORTED_SERVICES: [],
    SUPPORTED_STREAM_TYPES: [HTTP_STREAM_TYPE],
    SUPPORTED_RESOURCES: [STREAM_RESOURCE],
    OPTIONS: basicOptions('AStream'),
    CATEGORY: CATEGORY_STREAMS,
  },
  {
    ID: 'streamasia',
    NAME: 'StreamAsia',
    LOGO: 'https://streamasia.elfhosted.com/static/addon_logo_monochrome.png',
    URL: 'https://streamasia.elfhosted.com',
    DESCRIPTION: 'Asian content streaming addon.',
    SUPPORTED_SERVICES: [],
    SUPPORTED_STREAM_TYPES: [HTTP_STREAM_TYPE],
    SUPPORTED_RESOURCES: [STREAM_RESOURCE, CATALOG_RESOURCE],
    OPTIONS: basicOptions('StreamAsia'),
    CATEGORY: CATEGORY_STREAMS,
  },
  {
    ID: 'usa-tv',
    NAME: 'USA TV',
    LOGO: 'https://usa-tv.elfhosted.com/public/logo.png',
    URL: 'https://usa-tv.elfhosted.com',
    DESCRIPTION: 'Live US TV channels.',
    SUPPORTED_SERVICES: [],
    SUPPORTED_STREAM_TYPES: [LIVE_STREAM_TYPE],
    SUPPORTED_RESOURCES: [STREAM_RESOURCE, CATALOG_RESOURCE],
    OPTIONS: basicOptions('USA TV'),
    CATEGORY: CATEGORY_STREAMS,
  },
  {
    ID: 'argentina-tv',
    NAME: 'Argentina TV',
    LOGO: 'https://argentina-tv.elfhosted.com/public/logo.png',
    URL: 'https://argentina-tv.elfhosted.com',
    DESCRIPTION: 'Live Argentine TV channels.',
    SUPPORTED_SERVICES: [],
    SUPPORTED_STREAM_TYPES: [LIVE_STREAM_TYPE],
    SUPPORTED_RESOURCES: [STREAM_RESOURCE, CATALOG_RESOURCE],
    OPTIONS: basicOptions('Argentina TV'),
    CATEGORY: CATEGORY_STREAMS,
  },
  {
    ID: 'debridio-tv',
    NAME: 'Debridio TV',
    LOGO: 'https://debridio.com/logo.png',
    URL: 'https://debridio.com',
    DESCRIPTION: 'Live streaming of a wide variety of channels.',
    SUPPORTED_SERVICES: [],
    SUPPORTED_STREAM_TYPES: [LIVE_STREAM_TYPE],
    SUPPORTED_RESOURCES: [STREAM_RESOURCE, CATALOG_RESOURCE],
    OPTIONS: basicOptions('Debridio TV'),
    CATEGORY: CATEGORY_STREAMS,
  },
  {
    ID: 'debridio-watchtower',
    NAME: 'Debridio Watchtower',
    LOGO: 'https://debridio.com/logo.png',
    URL: 'https://debridio.com',
    DESCRIPTION: 'Watchtower is a http stream provider.',
    SUPPORTED_SERVICES: [],
    SUPPORTED_STREAM_TYPES: [HTTP_STREAM_TYPE],
    SUPPORTED_RESOURCES: [STREAM_RESOURCE],
    OPTIONS: basicOptions('Debridio Watchtower'),
    CATEGORY: CATEGORY_STREAMS,
  },
  {
    ID: 'debridio-ic4a',
    NAME: 'Debridio IC4A',
    LOGO: 'https://debridio.com/logo.png',
    URL: 'https://debridio.com',
    DESCRIPTION: 'IPTV backed livestreams from around the world. Provided by Debridio.',
    SUPPORTED_SERVICES: [],
    SUPPORTED_STREAM_TYPES: [LIVE_STREAM_TYPE],
    SUPPORTED_RESOURCES: [STREAM_RESOURCE, CATALOG_RESOURCE],
    OPTIONS: basicOptions('Debridio IC4A'),
    CATEGORY: CATEGORY_STREAMS,
  },
  {
    ID: 'torznab',
    NAME: 'Torznab',
    LOGO: '',
    URL: '',
    DESCRIPTION: 'An addon to get debrid results from a Torznab endpoint.',
    SUPPORTED_SERVICES: COMMON_DEBRID_SERVICES,
    SUPPORTED_STREAM_TYPES: [P2P_STREAM_TYPE, DEBRID_STREAM_TYPE],
    SUPPORTED_RESOURCES: [STREAM_RESOURCE],
    OPTIONS: basicOptions('Torznab'),
    CATEGORY: CATEGORY_STREAMS,
  },
  {
    ID: 'newznab',
    NAME: 'Newznab',
    LOGO: '',
    URL: '',
    DESCRIPTION: 'An addon to get usenet results from a Newznab endpoint.',
    SUPPORTED_SERVICES: [EASYNEWS_SERVICE],
    SUPPORTED_STREAM_TYPES: [USENET_STREAM_TYPE],
    SUPPORTED_RESOURCES: [STREAM_RESOURCE],
    OPTIONS: basicOptions('Newznab'),
    CATEGORY: CATEGORY_STREAMS,
  },
  {
    ID: 'doctor-who-universe',
    NAME: 'Doctor Who Universe',
    LOGO: 'https://i.imgur.com/zQ9Btju.png',
    URL: 'https://doctor-who.elfhosted.com',
    DESCRIPTION: 'Watch order for Doctor Who universe.',
    SUPPORTED_SERVICES: [],
    SUPPORTED_STREAM_TYPES: [],
    SUPPORTED_RESOURCES: [CATALOG_RESOURCE, META_RESOURCE],
    OPTIONS: basicOptions('Doctor Who Universe'),
    CATEGORY: CATEGORY_STREAMS,
  },

  // === META/CATALOG ADDONS ===
  {
    ID: 'tmdb-addon',
    NAME: 'The Movie Database',
    LOGO: 'https://raw.githubusercontent.com/mrcanelas/tmdb-addon/refs/heads/main/public/logo.png',
    URL: 'https://tmdb.elfhosted.com',
    DESCRIPTION: 'Provides rich metadata for movies and TV shows from TMDB',
    SUPPORTED_SERVICES: [],
    SUPPORTED_STREAM_TYPES: [],
    SUPPORTED_RESOURCES: [CATALOG_RESOURCE, META_RESOURCE],
    OPTIONS: basicOptions('TMDB'),
    CATEGORY: CATEGORY_META_CATALOGS,
  },
  {
    ID: 'debridio-tmdb',
    NAME: 'Debridio TMDB',
    LOGO: 'https://debridio.com/logo.png',
    URL: 'https://debridio.com',
    DESCRIPTION: 'Catalogs for the Debridio TMDB',
    SUPPORTED_SERVICES: [],
    SUPPORTED_STREAM_TYPES: [],
    SUPPORTED_RESOURCES: [CATALOG_RESOURCE, META_RESOURCE],
    OPTIONS: basicOptions('Debridio TMDB'),
    CATEGORY: CATEGORY_META_CATALOGS,
  },
  {
    ID: 'debridio-tvdb',
    NAME: 'Debridio TVDB',
    LOGO: 'https://debridio.com/logo.png',
    URL: 'https://debridio.com',
    DESCRIPTION: 'Catalogs for the Debridio TVDB',
    SUPPORTED_SERVICES: [],
    SUPPORTED_STREAM_TYPES: [],
    SUPPORTED_RESOURCES: [CATALOG_RESOURCE, META_RESOURCE],
    OPTIONS: basicOptions('Debridio TVDB'),
    CATEGORY: CATEGORY_META_CATALOGS,
  },
  {
    ID: 'streaming-catalogs',
    NAME: 'Streaming Catalogs',
    LOGO: 'https://play-lh.googleusercontent.com/TBRwjS_qfJCSj1m7zZB93FnpJM5fSpMA_wUlFDLxWAb45T9RmwBvQd5cWR5viJJOhkI',
    URL: 'https://streaming-catalogs.elfhosted.com',
    DESCRIPTION: 'Catalogs for your favourite streaming services!',
    SUPPORTED_SERVICES: [],
    SUPPORTED_STREAM_TYPES: [],
    SUPPORTED_RESOURCES: [CATALOG_RESOURCE, META_RESOURCE],
    OPTIONS: basicOptions('Streaming Catalogs'),
    CATEGORY: CATEGORY_META_CATALOGS,
  },
  {
    ID: 'anime-catalogs',
    NAME: 'Anime Catalogs',
    LOGO: 'https://anime-catalogs.elfhosted.com/addon-logo.png',
    URL: 'https://anime-catalogs.elfhosted.com',
    DESCRIPTION: 'Anime catalogs from various sources.',
    SUPPORTED_SERVICES: [],
    SUPPORTED_STREAM_TYPES: [],
    SUPPORTED_RESOURCES: [CATALOG_RESOURCE, META_RESOURCE],
    OPTIONS: basicOptions('Anime Catalogs'),
    CATEGORY: CATEGORY_META_CATALOGS,
  },
  {
    ID: 'torrent-catalogs',
    NAME: 'Torrent Catalogs',
    LOGO: 'https://i.ibb.co/w4BnkC9/GwxAcDV.png',
    URL: 'https://torrent-catalogs.elfhosted.com',
    DESCRIPTION: 'Browse popular torrent catalogs.',
    SUPPORTED_SERVICES: [],
    SUPPORTED_STREAM_TYPES: [],
    SUPPORTED_RESOURCES: [CATALOG_RESOURCE],
    OPTIONS: basicOptions('Torrent Catalogs'),
    CATEGORY: CATEGORY_META_CATALOGS,
  },
  {
    ID: 'rpdb-catalogs',
    NAME: 'RPDB Catalogs',
    LOGO: 'https://rpdb-catalogs.elfhosted.com/addon-logo.png',
    URL: 'https://rpdb-catalogs.elfhosted.com',
    DESCRIPTION: 'Catalogs to accurately track new / popular / best release!',
    SUPPORTED_SERVICES: [],
    SUPPORTED_STREAM_TYPES: [],
    SUPPORTED_RESOURCES: [CATALOG_RESOURCE, META_RESOURCE],
    OPTIONS: basicOptions('RPDB Catalogs'),
    CATEGORY: CATEGORY_META_CATALOGS,
  },
  {
    ID: 'tmdb-collections',
    NAME: 'TMDB Collections',
    LOGO: 'https://raw.githubusercontent.com/youchi1/tmdb-collections/main/Images/logo.png',
    URL: 'https://tmdb-collections.elfhosted.com',
    DESCRIPTION: 'Catalogs for the TMDB Collections',
    SUPPORTED_SERVICES: [],
    SUPPORTED_STREAM_TYPES: [],
    SUPPORTED_RESOURCES: [CATALOG_RESOURCE, META_RESOURCE],
    OPTIONS: basicOptions('TMDB Collections'),
    CATEGORY: CATEGORY_META_CATALOGS,
  },
  {
    ID: 'anime-kitsu',
    NAME: 'Anime Kitsu',
    LOGO: 'https://i.imgur.com/7N6XGoO.png',
    URL: 'https://anime-kitsu.strem.fun',
    DESCRIPTION: 'Anime catalog using Kitsu',
    SUPPORTED_SERVICES: [],
    SUPPORTED_STREAM_TYPES: [],
    SUPPORTED_RESOURCES: [CATALOG_RESOURCE, META_RESOURCE],
    OPTIONS: basicOptions('Anime Kitsu'),
    CATEGORY: CATEGORY_META_CATALOGS,
  },
  {
    ID: 'marvel-universe',
    NAME: 'Marvel Universe',
    LOGO: 'https://upload.wikimedia.org/wikipedia/commons/b/b9/Marvel_Logo.svg',
    URL: 'https://marvel.elfhosted.com',
    DESCRIPTION: 'Catalogs for the Marvel Universe',
    SUPPORTED_SERVICES: [],
    SUPPORTED_STREAM_TYPES: [],
    SUPPORTED_RESOURCES: [CATALOG_RESOURCE, META_RESOURCE],
    OPTIONS: basicOptions('Marvel Universe'),
    CATEGORY: CATEGORY_META_CATALOGS,
  },
  {
    ID: 'star-wars-universe',
    NAME: 'Star Wars Universe',
    LOGO: 'https://www.freeiconspng.com/uploads/logo-star-wars-png-4.png',
    URL: 'https://star-wars.elfhosted.com',
    DESCRIPTION: 'Watch order for Star Wars universe.',
    SUPPORTED_SERVICES: [],
    SUPPORTED_STREAM_TYPES: [],
    SUPPORTED_RESOURCES: [CATALOG_RESOURCE, META_RESOURCE],
    OPTIONS: basicOptions('Star Wars Universe'),
    CATEGORY: CATEGORY_META_CATALOGS,
  },
  {
    ID: 'dc-universe',
    NAME: 'DC Universe',
    LOGO: 'https://raw.githubusercontent.com/tapframe/addon-dc/refs/heads/main/assets/icon.png',
    URL: 'https://dc.elfhosted.com',
    DESCRIPTION: 'Watch order for DC universe.',
    SUPPORTED_SERVICES: [],
    SUPPORTED_STREAM_TYPES: [],
    SUPPORTED_RESOURCES: [CATALOG_RESOURCE, META_RESOURCE],
    OPTIONS: basicOptions('DC Universe'),
    CATEGORY: CATEGORY_META_CATALOGS,
  },
  {
    ID: 'ai-companion',
    NAME: 'AI Companion',
    LOGO: 'https://raw.githubusercontent.com/willtho89/stremio-ai-companion/refs/heads/main/.assets/logo2_256.png',
    URL: 'https://ai-companion.elfhosted.com',
    DESCRIPTION: 'Your AI-powered movie and series recommendations.',
    SUPPORTED_SERVICES: [],
    SUPPORTED_STREAM_TYPES: [],
    SUPPORTED_RESOURCES: [CATALOG_RESOURCE, META_RESOURCE],
    OPTIONS: basicOptions('AI Companion'),
    CATEGORY: CATEGORY_META_CATALOGS,
  },
  {
    ID: 'ai-search',
    NAME: 'AI Search',
    LOGO: 'https://raw.githubusercontent.com/itcon-pty-au/stremio-ai-search/refs/heads/main/public/logo.png',
    URL: 'https://ai-search.elfhosted.com',
    DESCRIPTION: 'AI-powered search for movies and series.',
    SUPPORTED_SERVICES: [],
    SUPPORTED_STREAM_TYPES: [],
    SUPPORTED_RESOURCES: [CATALOG_RESOURCE, META_RESOURCE],
    OPTIONS: basicOptions('AI Search'),
    CATEGORY: CATEGORY_META_CATALOGS,
  },
  {
    ID: 'more-like-this',
    NAME: 'More Like This',
    LOGO: 'https://raw.githubusercontent.com/rama1997/More-Like-This/refs/heads/main/assets/images/logo.jpg',
    URL: 'https://more-like-this.elfhosted.com',
    DESCRIPTION: 'Shows recommendations from various sources',
    SUPPORTED_SERVICES: [],
    SUPPORTED_STREAM_TYPES: [],
    SUPPORTED_RESOURCES: [CATALOG_RESOURCE, META_RESOURCE],
    OPTIONS: basicOptions('More Like This'),
    CATEGORY: CATEGORY_META_CATALOGS,
  },

  // === SUBTITLE ADDONS ===
  {
    ID: 'opensubtitles',
    NAME: 'OpenSubtitles v3',
    LOGO: 'https://iwf1.com/scrapekod/icons/service.subtitles.opensubtitles_by_opensubtitles_dualsub.png',
    URL: 'https://opensubtitles-v3.strem.io',
    DESCRIPTION: 'OpenSubtitles addon',
    SUPPORTED_SERVICES: [],
    SUPPORTED_STREAM_TYPES: [],
    SUPPORTED_RESOURCES: [SUBTITLES_RESOURCE],
    OPTIONS: basicOptions('OpenSubtitles'),
    CATEGORY: CATEGORY_SUBTITLES,
  },
  {
    ID: 'opensubtitles-v3-plus',
    NAME: 'OpenSubtitles V3 Pro',
    LOGO: 'https://i.ibb.co/yN39ZPV/opensubtitles-plus-256x256.png',
    URL: 'https://opensubtitles-v3-plus.elfhosted.com',
    DESCRIPTION: 'Enhanced OpenSubtitles with more features.',
    SUPPORTED_SERVICES: [],
    SUPPORTED_STREAM_TYPES: [],
    SUPPORTED_RESOURCES: [SUBTITLES_RESOURCE],
    OPTIONS: basicOptions('OpenSubtitles V3 Pro'),
    CATEGORY: CATEGORY_SUBTITLES,
  },
  {
    ID: 'subsource',
    NAME: 'SubSource',
    LOGO: 'https://raw.githubusercontent.com/nexusdiscord/tv-logo/master/ss.png',
    URL: 'https://subsource.elfhosted.com',
    DESCRIPTION: 'SubSource addon',
    SUPPORTED_SERVICES: [],
    SUPPORTED_STREAM_TYPES: [],
    SUPPORTED_RESOURCES: [SUBTITLES_RESOURCE],
    OPTIONS: basicOptions('SubSource'),
    CATEGORY: CATEGORY_SUBTITLES,
  },
  {
    ID: 'subdl',
    NAME: 'SubDL',
    LOGO: 'https://raw.githubusercontent.com/nexusdiscord/tv-logo/master/download.jpg',
    URL: 'https://subdl.elfhosted.com',
    DESCRIPTION: 'SubDL addon',
    SUPPORTED_SERVICES: [],
    SUPPORTED_STREAM_TYPES: [],
    SUPPORTED_RESOURCES: [SUBTITLES_RESOURCE],
    OPTIONS: basicOptions('SubDL'),
    CATEGORY: CATEGORY_SUBTITLES,
  },
  {
    ID: 'subhero',
    NAME: 'SubHero',
    LOGO: 'https://images.icon-icons.com/3606/PNG/512/sculpture_statue_texture_futuristic_art_geometry_organic_abstract_shape_explode_shae_icon_226539.png',
    URL: 'https://subhero.elfhosted.com',
    DESCRIPTION: 'Subtitles provided & scraped by Wyzie API',
    SUPPORTED_SERVICES: [],
    SUPPORTED_STREAM_TYPES: [],
    SUPPORTED_RESOURCES: [SUBTITLES_RESOURCE],
    OPTIONS: basicOptions('SubHero'),
    CATEGORY: CATEGORY_SUBTITLES,
  },
  {
    ID: 'aiosubtitle',
    NAME: 'AIO Subtitle',
    LOGO: 'https://aiosubtitle.elfhosted.com/assets/AI-sub.png',
    URL: 'https://aiosubtitle.elfhosted.com',
    DESCRIPTION: 'AI-powered subtitle addon.',
    SUPPORTED_SERVICES: [],
    SUPPORTED_STREAM_TYPES: [],
    SUPPORTED_RESOURCES: [SUBTITLES_RESOURCE],
    OPTIONS: basicOptions('AIO Subtitle'),
    CATEGORY: CATEGORY_SUBTITLES,
  },

  // === MISC ADDONS ===
  {
    ID: 'custom',
    NAME: 'Custom',
    LOGO: '',
    URL: '',
    DESCRIPTION: 'Add your own addon by providing its Manifest URL.',
    SUPPORTED_SERVICES: [],
    SUPPORTED_STREAM_TYPES: [P2P_STREAM_TYPE, DEBRID_STREAM_TYPE, HTTP_STREAM_TYPE, USENET_STREAM_TYPE, LIVE_STREAM_TYPE],
    SUPPORTED_RESOURCES: [STREAM_RESOURCE, CATALOG_RESOURCE, META_RESOURCE, SUBTITLES_RESOURCE],
    OPTIONS: [
      { id: 'url', name: 'Manifest URL', description: 'The URL to the addon manifest.json', type: 'url', required: true },
      ...basicOptions('Custom Addon'),
    ],
    CATEGORY: CATEGORY_MISC,
  },
  {
    ID: 'aiostreams',
    NAME: 'AIOStreams',
    LOGO: 'https://raw.githubusercontent.com/Viren070/AIOStreams/refs/heads/main/packages/frontend/public/assets/logo.png',
    URL: '',
    DESCRIPTION: 'Wrap AIOStreams within AIOStreams!',
    SUPPORTED_SERVICES: [],
    SUPPORTED_STREAM_TYPES: [DEBRID_STREAM_TYPE],
    SUPPORTED_RESOURCES: [STREAM_RESOURCE],
    OPTIONS: basicOptions('AIOStreams'),
    CATEGORY: CATEGORY_MISC,
  },
  {
    ID: 'content-deep-dive',
    NAME: 'Content Deep Dive',
    LOGO: 'https://content-deep-dive.elfhosted.com/DeepDiveLogo.png',
    URL: 'https://content-deep-dive.elfhosted.com',
    DESCRIPTION: 'Deep dive into content details.',
    SUPPORTED_SERVICES: [],
    SUPPORTED_STREAM_TYPES: [],
    SUPPORTED_RESOURCES: [META_RESOURCE],
    OPTIONS: basicOptions('Content Deep Dive'),
    CATEGORY: CATEGORY_MISC,
  },
];

// Mock status response for frontend-only deployment
const mockStatusResponse = {
  version: '2.20.0',
  tag: 'frontend-only',
  commit: 'frontend-deployment',
  buildTime: new Date().toISOString(),
  commitTime: new Date().toISOString(),
  users: null,
  settings: {
    baseUrl: process.env.BASE_URL || 'https://aiostreams.vercel.app',
    addonName: 'AIOStreams',
    alternateDesign: false,
    protected: false,
    regexFilterAccess: 'none' as const,
    loggingSensitiveInfo: false,
    tmdbApiAvailable: false,
    forced: {
      proxy: {
        enabled: null,
        id: null,
        url: null,
        publicUrl: null,
        publicIp: null,
        credentials: null,
        disableProxiedAddons: false,
        proxiedServices: null,
      },
    },
    defaults: {
      proxy: {
        enabled: null,
        id: null,
        url: null,
        publicUrl: null,
        publicIp: null,
        credentials: null,
        proxiedServices: null,
      },
      timeout: null,
    },
    presets,
    services,
    limits: {
      maxMergedCatalogSources: 10,
    },
  },
};

export async function GET() {
  return NextResponse.json({
    success: true,
    data: mockStatusResponse,
  });
}
